# Generated by Django 5.2.1 on 2025-05-26 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DimJogo",
            fields=[
                ("jogo_id", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("ano", models.IntegerField()),
                ("categoria", models.CharField(max_length=100)),
                ("duracao", models.IntegerField()),
            ],
            options={
                "db_table": "dw.dim_jogo",
            },
        ),
        migrations.CreateModel(
            name="DimTempo",
            fields=[
                ("tempo_id", models.AutoField(primary_key=True, serialize=False)),
                ("data_venda", models.DateField(unique=True)),
                ("ano", models.IntegerField()),
                ("mes", models.IntegerField()),
                ("dia", models.IntegerField()),
            ],
            options={
                "db_table": "dw.dim_tempo",
            },
        ),
        migrations.CreateModel(
            name="FatoVenda",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantidade", models.IntegerField()),
                (
                    "jogo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="etl.dimjogo"
                    ),
                ),
                (
                    "tempo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="etl.dimtempo"
                    ),
                ),
            ],
            options={
                "db_table": "dw.fato_venda",
            },
        ),
    ]
